### ISSUE TITLE
Vue-breadcrumbs breaks webpage on IE 10

### ISSUE THREAD

**Issue by marcosPerezRubio** [samturrell/vue-breadcrumbs#13]
Hello!

As vue-breadcrumbs uses Object.assign, this causes IE 10 to not load the webpage because it can not support it. 

This is easily solvable by adding the babel polyfill (https://babeljs.io/docs/plugins/transform-object-assign/).

Could this be implemented in a future release?

Thanks!

**Comment by samturrell** [comment]
Hi @marcosPerezRubio - I would probably say it's better to add the polyfill to your implementation rather than it being added to the core of the plugin as it would create unnecessary overhead for browsers that have native support.

**Comment by marcosPerezRubio** [comment]
Agree with that!

Thanks for your response :)

Marcos Pérez
