### ISSUE TITLE
Breadcrumb doesn't works with I pass params via vue-router

### ISSUE THREAD

**Issue by ivomarsan** [samturrell/vue-breadcrumbs#15]
When I have an usual route like:
```javascript
/issue
```
![Without ID](https://image.prntscr.com/image/A1GNSNmETQK5BWSbBFXCtg.png)
Every thing is OK! But when I have passing properties, something happen.
```javascript
/issue/:id
```
![With ID](https://image.prntscr.com/image/w634URmHR1OicjsDERtpwA.png)
And the links on breadcrumbs be `localhost:8080/#/issue/:id` but doesn't make sense. Should be only `localhost:8080/#/issue`. Help me

**Comment by samturrell** [comment]
Hi @ivomarsan - could you provide some example code that i can use to reproduce?

**Comment by ivomarsan** [comment]
Sorry, I saw now, You use `children` in VueRouter to pass a `:id` property. Solveed!

**Comment by sreecodeslayer** [comment]
I came across this issue today, here is an example of the route(s) that are having this issue.

When the expected path for the crumb `RouteB` is `http://127.0.0.1:8080/#/route_a/1/route_b`, I am getting `http://127.0.0.1:8080/#/route_a/:aid/route_b`
Now, if I extend the `RouteC` further to another child, then that too will have the same issue extended to `:cid`

Naming the route as stated in this [issue](https://github.com/samturrell/vue-breadcrumbs/issues/12) doesn't seem to fix it for me
```javascript
{
	path: '/route_a',
	name: 'RouteA',
	component: RouteA,
	meta: { breadcrumb: "RouteA"},
	children:[{
		path: ':aid/route_b',
		name: 'RouteB',
		component: RouteB,
		meta: { breadcrumb: "RouteB" },
		children: [{
			path: ':cid',
			name: 'RouteC',
			component: RouteC,
			meta: {	breadcrumb: "RouteC" }
		}]
	}]
}
```

**Comment by sreecodeslayer** [comment]
Got it to work by adding [this method](https://github.com/samturrell/vue-breadcrumbs/blob/master/src/index.js#L40) to the `methods`. Had to dig around the source as I couldn't really figure it out from the given example. :smile:
