### ISSUE TITLE
linkProp issues

### ISSUE THREAD

**Issue by luminous8** [samturrell/vue-breadcrumbs#17]
Hi, 

I just tried this plugin but got this error by using the example : 
`Property or method "linkProp" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property
`
& 

`"Error in render: "TypeError: _vm.linkProp is not a function"`

I'm not really sure what I'm doing wrong, any one could help me?

Thanks!

**Comment by samturrell** [comment]
Hi @luminous8 - did you find the solution to your problem? Would it help anybody else that may come across this issue?

**Comment by luminous8** [comment]
Yes! Actually I didn't get it right how to properly use it. I get it by looking at the example.
Maybe in the doc you should precise that even we import like this import VueBreadcrumbs from 'vue-breadcrumbs' we do not need to import it as a component as it is already declared and simply use in with this tag in your code <breadcrumbs></breadcrumbs>
