### ISSUE TITLE
Don't work (Meteor + Element UI)

### ISSUE THREAD

**Issue by thearabbit** [samturrell/vue-breadcrumbs#9]
I base on `Meteor + Element UI`.
get error
```js
printer.js:170 [Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build. 
(found in <Breadcrumbs>)
```

**Comment by samturrell** [comment]
Hi @thearabbit - Would you be able to provide an example repository with the error?

**Comment by andycaramba** [comment]
Hi. I have this error too.

If install vue with npm and without `<script src="https://cdn.jsdelivr.net/vue/2.3.0/vue.js"></script>` in `index.html`
Then use it this manner
```javascript
import Vue from 'vue';
import VueRouter from 'vue-router';
import VueBreadcrumbs from 'vue-breadcrumbs';

Vue.use(VueRouter);
Vue.use(VueBreadcrumbs, {
  template: `<nav class="breadcrumb" v-if="$breadcrumbs.length">
    <router-link class="breadcrumb-item" v-for="(crumb, key) in $breadcrumbs" :to="linkProp(crumb)" :key="key">'
      {{ crumb | crumbText }}
    </router-link>
  </nav>`,
});
...
...
...etc
```

Following error will be occurred
```
[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

found in

---> <Breadcrumbs>
          ...other router components
```
and no breadcrumbs will be rendered

**Comment by andycaramba** [comment]
The following code in webpack config solves this problem for me
```javascript
resolve: {
  alias: {
    vue$: 'vue/dist/vue.esm.js',
  },
},
```
from [Vue.js Forum](https://forum.vuejs.org/t/vue-2-0-warn-you-are-using-the-runtime-only-build-of-vue-where-the-template-compiler-is-not-available/9429/3) and [Vue Explanation of Build Files](https://github.com/vuejs/vue/tree/dev/dist)

**Comment by samturrell** [comment]
Thanks @andycaramba!

**Comment by thearabbit** [comment]
@andycaramba, where you put this `resolve: {...........`?

**Comment by andycaramba** [comment]
Hi @thearabbit 
I use webpack as build tool in my project and I put above strings to my webpack config. See [here](https://webpack.js.org/configuration/resolve/) for docs and [here](https://github.com/vuejs/vue-hackernews-2.0/blob/4f92d4ec184aad36c1b451740adacd4905d1e90f/build/webpack.base.config.js#L23) for example (I just add `vue$: 'vue/dist/vue.esm.js',` to this block)

P.S. I don't know how to use it with Meteor. See Meteor docs or try to ask StackOverflow.

**Comment by thearabbit** [comment]
Thanks again.
